# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

# need tz for pcap files but wireless/pcap uses alpine - see wlan_start.sh
# but need to put in each service
    
services:


    rredis:
        image: redis:4.0.5-alpine
        container_name: redis_cache
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
        command: ["redis-server", "--appendonly", "yes"]
        hostname: rredis
        ports:
            - "6379:6379"
        volumes:
            - type: bind
              target: /redis_data
              source: /testbed/redis_data
        #restart: always


    wireless: # pcap and wireless interface
        build: ./wireless
        network_mode: "host"
        environment:
            - INTERFACE=$WIRELESSINTERFACE #wlp2s0
            - DEBUG="1"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        privileged: true
        tty: true
        volumes: 
            - type: bind
              target: /pcaps
              source: /testbed/pcaps
            - type: bind
              target: /filedrop
              source: /testbed/filedrop

        #restart: always
        
           
    describe:
        build: ./describe
        tty: true
        volumes: 
            - type: bind
              target: /pcaps
              source: /testbed/pcaps
            - type: bind
              target: /testpcaps
              source: /testbed/testpcaps
            - type: bind
              target: /reports
              source: /testbed/reports
        ports:
            - "3000:3000"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        depends_on:
           - rredis
        #restart: always
        links:
           - rredis

    snort:
        build: ./snort
        ports: 
        - "8080:8080"
        environment:
            - INTERFACE=$SNORTINTERFACE
            - HOST_NET="192.168.1.0/8"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
            - OINKCODE=$OINKCODE
        volumes: 
            - type: bind
              target: /pcaps
              source: /testbed/pcaps
            - type: bind
              target: /reports
              source: /testbed/reports
            - type: bind
              target: /testpcaps
              source: /testbed/testpcaps
        depends_on:
            - rredis 
        #restart: always
        links:
            - rredis

    pentest:
        build: ./pentest
        # network_mode: "host"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        volumes: 
            - type: bind
              target: /pcaps
              source: /testbed/pcaps
            - type: bind
              target: /reports
              source: /testbed/reports
            - type: bind
              target: /testpcaps
              source: /testbed/testpcaps
        depends_on:
            - rredis 
        #restart: always
        links:
            - rredis




#volumes: 
    #pcaps:
      #external: true
    #reports: 
      #external: true
    #redis_data:
      #external: true
    #filedrop:
      #external: true
