# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

# need tz for pcap files but wireless/pcap uses alpine - see wlan_start.sh
# but need to put in each service
# PUT YOUR OINKCODE in .env
# as OINKCODE=xxxxxxxx..
    
services:


    rredis:
        image: redis:4.0.5-alpine
        container_name: redis_cache
        network_mode: bridge
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
        command: ["redis-server", "--appendonly", "yes"]
        hostname: rredis
        ports:
            - 6379:6379
        volumes:
        - ./testbed/redis_data:/redis_data
        - ./testbed/apk_cache:/etc/apk/cache
        
        #restart: always


    wireless: # pcap and wireless interface
        build: ./wireless
        network_mode: host
        environment:
            - INTERFACE=$WIRELESSINTERFACE
            - DEBUG=1
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
            - REDIS_URL=redis://redis_cache:6379
            - WIRELESSINTERFACE=$WIRELESSINTERFACE
            - SNORTINTERFACE=$WIRELESSINTERFACE
            - WSSID=$WIRELESS_SSID
            - WPAPASSPHRASE=$WPAPASSPHRASE
            - ./testbed/apk_cache:/etc/apk/cache
        privileged: true
        #tty: true
        volumes: 
        - ./testbed/pcaps:/pcaps
        - ./testbed/filedrop:/filedrop
        - ./testbed/testpcaps:/testpcaps

        #restart: always
           
    describe:
        build: ./describe
        links:
          - rredis
        tty: true
        network_mode: bridge
        volumes:
        - ./testbed/pcaps:/pcaps
        - ./testbed/reports:/reports
        - ./testbed/testpcaps:/testpcaps
        - ./testbed/html:/var/www/html
        - ./testbed/apt_cache:/var/cache/apt
        - ./testbed/rq:/rq
        ports:
            - 3000:3000
            - 9999:9999 # rq-dashboard
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
            - REDIS_URL=redis://rredis:6379
        depends_on:
           - rredis
        #restart: always

    suricata:
        build: ./suricata
        network_mode: bridge
        links:
          - rredis
        volumes:
        - ./testbed/pcaps:/pcaps
        - ./testbed/reports:/reports
        - ./testbed/testpcaps:/testpcaps
        - ./testbed/html:/var/www/html
        - ./testbed/apt_cache:/var/cache/apt
        - ./testbed/rq:/rq
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
            - REDIS_URL=redis://rredis:6379 
        depends_on:
           - rredis
        #restart: always

    pentest:
        build: ./pentest
        network_mode: bridge
        links:
          - rredis
        volumes:
        - ./testbed/pcaps:/pcaps
        - ./testbed/reports:/reports
        - ./testbed/testpcaps:/testpcaps
        - ./testbed/html:/var/www/html
        - ./testbed/apt_cache:/var/cache/apt
        - ./testbed/rq:/rq
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
            - REDIS_URL=redis://rredis:6379 
        depends_on:
           - rredis
        #restart: always

    snort:
        build: ./snortubu
        network_mode: bridge
        links:
          - rredis 
        ports: 
        - 8080:8080
        environment:
            - INTERFACE=$SNORTINTERFACE
            - HOME_NET=$HOME_NET
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - TZ=Australia/Sydney
            - REDIS_URL=redis://rredis:6379  
            - OINKCODE=$OINKCODE # put yours in .env
        volumes: 
        - ./testbed/pcaps:/pcaps
        - ./testbed/reports:/reports
        - ./testbed/testpcaps:/testpcaps
        - ./testbed/apt_cache:/var/cache/apt
        - ./testbed/rq:/rq
        depends_on:
            - rredis 
        #restart: always
        links:
          - rredis




