# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

services:
    wireless: # pcap and wireless interface
        build: 
           ./wireless
        network_mode: "host"
        environment:
            - INTERFACE=wlp2s0
            - DEBUG="1"
        privileged: true
        tty: true
        volumes: 
            - "pcaps: /testbed/pcaps"
        
           
    describe:
        build: ./describe
        tty: true
        volumes: 
            - "pcaps: /testbed/pcaps"
            - "reports: /testbed/reports"
        ports:
            - 3000:3000
        

    snort:
        image: snort
        # network_mode: "host"
        ports: 
        - "8080:8080"
        environment:
            INTERFACE: "enp0s25"
            HOST_NET: "192.168.1.0/8"
        volumes:
            - "pcaps: /testbed/pcaps"

volumes: 
    pcaps:
    reports: 
  
