# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

# need tz for pcap files but wireless/pcap uses alpine - see wlan_start.sh
# but need to put in each service
# PUT YOUR OINKCODE in .env
# as OINKCODE=xxxxxxxx..
    
services:


    rredis:
        image: redis:4.0.5-alpine
        container_name: redis_cache
        network_mode: "bridge"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
        command: ["redis-server", "--appendonly", "yes"]
        hostname: rredis
        ports:
            - "6379:6379"
        volumes:
        - /testbed/redis_data:/redis_data
        #restart: always


    wireless: # pcap and wireless interface
        build: ./wireless
        network_mode: "host"
        environment:
            - INTERFACE=$WIRELESSINTERFACE #wlp2s0
            - DEBUG="1"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        privileged: true
        tty: true
        volumes: 
        - /testbed/pcaps:/pcaps
        - /testbed/filedrop:/filedrop
        - /testbed/testpcaps:/testpcaps

        #restart: always
        
           
    describe:
        build: ./describe
        tty: true
        network_mode: "bridge"
        volumes:
        - /testbed/pcaps:/pcaps
        - /testbed/reports:/reports
        - /testbed/testpcaps:/testpcaps
        - /testbed/html:/var/www/html
        ports:
            - "3000:3000"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        depends_on:
           - rredis
        #restart: always


    snort:
        build: ./snortubu
        network_mode: "bridge"
        ports: 
        - "8080:8080"
        environment:
            - INTERFACE=$SNORTINTERFACE
            - HOST_NET="192.168.1.0/8"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
            - OINKCODE=$OINKCODE # put yours in .env
        volumes: 
        - /testbed/pcaps:/pcaps
        - /testbed/reports:/reports
        - /testbed/testpcaps:/testpcaps
        depends_on:
            - rredis 
        #restart: always
        # links:
        #   - rredis

    pentest:
        build: ./pentest
        network_mode: "host"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        volumes: 
        - /testbed/pcaps:/pcaps
        - /testbed/reports:/reports
        - /testbed/testpcaps:/testpcaps
        depends_on:
            - rredis 
        #restart: always
        #links:
        #   - rredis




