# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

# need tz for pcap files but wireless/pcap uses alpine - see wlan_start.sh
# but need to put in each service
    
services:
    wireless: # pcap and wireless interface
        build: 
           ./wireless
        network_mode: "host"
        environment:
            - INTERFACE=wlp2s0
            - DEBUG="1"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
        privileged: true
        tty: true
        volumes: 
            - "/testbed/pcaps:/pcaps"
        
           
    describe:
        build: ./describe
        tty: true
        volumes: 
            - "/testbed/pcaps:/pcaps"
            - "/testbed/reports:/reports"
        ports:
            - 3000:3000
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"

    snort:
        image: snort
        # network_mode: "host"
        ports: 
        - "8080:8080"
        environment:
            - INTERFACE="enp0s25"
            - HOST_NET="192.168.1.0/8"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
        volumes:
            - "/testbed/pcaps:/pcaps"


volumes: 
    pcaps:
    reports: 
  
