# docker-compose.yml
# wierd things happen with indentation issues

version: "3.7"

# need tz for pcap files but wireless/pcap uses alpine - see wlan_start.sh
# but need to put in each service
    
services:


    redis:
        image: redis:4.0.5-alpine
        container_name: redis_cache
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
          - "redis_data:/testbed/redis_data"
        restart: always


    wireless: # pcap and wireless interface
        build: 
           ./wireless
        network_mode: "host"
        environment:
            - INTERFACE=wlp2s0
            - DEBUG="1"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        privileged: true
        tty: true
        volumes: 
            - "/testbed/pcaps:/pcaps"

        # restart: always
        
           
    describe:
        build: ./describe
        tty: true
        volumes: 
            - "/testbed/pcaps:/pcaps"
            - "/testbed/reports:/reports"
        ports:
            - 3000:3000
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        #depends_on:
        #   - redis
        #restart: always
        #links:
        #    - redis

    snort:
        image: snort
        ports: 
        - "8080:8080"
        environment:
            - INTERFACE="enp0s25"
            - HOST_NET="192.168.1.0/8"
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        volumes:
            - "/testbed/pcaps:/pcaps"
        depends_on:
            - redis 
        restart: always
        links:
            - redis

    pentest:
        image: pentest
        # network_mode: "host"
        environment:
            - LANG="en_US.UTF-8"
            - LANGUAGE="en_US.UTF-8"
            - TZ="Australia/Sydney"
            - REDIS_URL=redis://redis_cache
        volumes:
            - "/testbed/reports:/reports"
        depends_on:
            - redis 
        restart: always
        links:
            - redis


volumes: 
    pcaps:
    reports: 
    redis_data:
